### ISSUE TITLE
Newton step for FaithfulNormalOptimization

### ISSUE THREAD

**Issue by JohnLaMaster** [astirn/faithful-heteroscedasticity#1]
In your paper, Proposal I replaces the gradient step with a Newton step. This is also done in the [code](https://github.com/astirn/faithful-heteroscedasticity/blob/main/models.py?plain=1#L150) in function Proposal1Normal on [line 167](https://github.com/astirn/faithful-heteroscedasticity/blob/main/models.py?plain=1#L167). However, it doesn't look like this was implemented in FaithfulNormalOptimization function. I'm trying to implement this in PyTorch, so I'd really appreciate your insight.

**Comment by astirn** [comment]
Thanks for your interest! The Newton step is implicit--the `opimization_step` routine in the `FaithfulNormalOptimization` class (lines 197-204) implements our alternative loss (equation 5 from [our paper](https://proceedings.mlr.press/v206/stirn23a/stirn23a.pdf)). Per theorem 1, the gradient of this loss w.r.t. the mean is the same as SSE loss, which in turn is a Newton step for a heteroscedastic loss. I hope that helps. Let me know if you have further questions!
